// BASIC DSA (Part 1) — Array & String algorithms, 12 topics.
// 96 unique problems.
// Arrays: 17 · Strings: 5 · Sliding Window: 3 · Two Pointers: 2 · Prefix Sum: 1 · Binary Search: 11 · Sorting: 10 · Recursion: 5 · Backtracking: 10 · Greedy: 8 · Bit Manipulation: 10 · Math: 14
export const dsaBasicProblems = [
  // ===== Arrays =====
  {
    id: 1,
    title: "Trapping Rain Water",
    topic: "Arrays",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/trapping-rain-water/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=6z9hrVpUm6s",
  },
  {
    id: 2,
    title: "Maximum of Absolute Value Expression",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/maximum-of-absolute-value-expression/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 3,
    title: "Range Sum Query",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/range-sum-query-immutable/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=EGpZNRtvj2U",
  },
  {
    id: 4,
    title: "Range Sum Query 2D",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/range-sum-query-2d-immutable/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=xB7WBIc-LHQ",
  },
  {
    id: 5,
    title: "Search a 2D Matrix",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/search-a-2d-matrix/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=dAWKp8_GtUc",
  },
  {
    id: 6,
    title: "Max Chunks To Make Sorted",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/max-chunks-to-make-sorted/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=Ekc84QC4oFQ",
  },
  {
    id: 7,
    title: "Spiral Matrix",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/spiral-matrix/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=FlvgvbPvgxE",
  },
  {
    id: 8,
    title: "Matrix Diagonal Sum",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/matrix-diagonal-sum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 9,
    title: "Sum of all Submatrices",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/sum-of-all-submatrices-of-a-given-matrix/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 10,
    title: "Next Permutation",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/next-permutation/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=SEMS-0d4X6Q",
  },
  {
    id: 11,
    title: "Set Matrix Zeroes",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/set-matrix-zeroes/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=mFsoVAfMM0A",
  },
  {
    id: 12,
    title: "Maximum Subarray",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/maximum-subarray/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=06cO3EPoWes",
  },
  {
    id: 13,
    title: "Maximum Gap",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/maximum-gap/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 14,
    title: "Array Zero Split and Merge",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/check-whether-an-array-can-be-made-0-by-splitting-and-merging-repeatedly/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 15,
    title: "Concatenation of Array",
    topic: "Arrays",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/concatenation-of-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 16,
    title: "Partition Array According to Given Pivot",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/partition-array-according-to-given-pivot/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 17,
    title: "Find Pairs in Array Whose Sums Already Exist",
    topic: "Arrays",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/find-pairs-in-array-whose-sums-already-exist-in-array/",
    platform: "gfg",
    videoLink: null,
  },

  // ===== Strings =====
  {
    id: 18,
    title: "Palindrome Pairs",
    topic: "Strings",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/palindrome-pairs/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 19,
    title: "Letter Case Permutation",
    topic: "Strings",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/letter-case-permutation/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 20,
    title: "Backspace String Compare",
    topic: "Strings",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/backspace-string-compare/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 21,
    title: "Longest Substring Without Repeating Characters",
    topic: "Strings",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=liT9Z467sa4",
  },
  {
    id: 22,
    title: "Longest Substring with K Uniques",
    topic: "Strings",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/problems/longest-k-unique-characters-substring0853/1",
    platform: "gfg",
    videoLink: null,
  },

  // ===== Sliding Window =====
  {
    id: 23,
    title: "Sliding Window Maximum",
    topic: "Sliding Window",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/sliding-window-maximum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 24,
    title: "Minimum Window Substring",
    topic: "Sliding Window",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/minimum-window-substring/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=sbZ2mhi7aIw",
  },
  {
    id: 25,
    title: "Max Sum Subarray of Size K",
    topic: "Sliding Window",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/window-sliding-technique/",
    platform: "gfg",
    videoLink: null,
  },

  // ===== Two Pointers =====
  {
    id: 26,
    title: "Container With Most Water",
    topic: "Two Pointers",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/container-with-most-water/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=v4HvnH6L_cM",
  },
  {
    id: 27,
    title: "Valid Palindrome",
    topic: "Two Pointers",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/valid-palindrome/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== Prefix Sum =====
  {
    id: 28,
    title: "Subarray Sum Equals K",
    topic: "Prefix Sum",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/subarray-sum-equals-k/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== Binary Search =====
  {
    id: 29,
    title: "Binary Search",
    topic: "Binary Search",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/binary-search/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=JpeuTaAVBiA",
  },
  {
    id: 30,
    title: "Find First and Last Position of Element",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=6tAmm8JjyDY",
  },
  {
    id: 31,
    title: "Single Element in a Sorted Array",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/single-element-in-a-sorted-array/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=Pm-e0N2gxqc",
  },
  {
    id: 32,
    title: "Find Minimum in Rotated Sorted Array",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=vopmtrYOx-s",
  },
  {
    id: 33,
    title: "Search in Rotated Sorted Array",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=jbIzK1jZMhc",
  },
  {
    id: 34,
    title: "Maximum in a Sorted and Rotated Array",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/maximum-element-in-a-sorted-and-rotated-array/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 35,
    title: "Find Peak Element",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-peak-element/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=xga-GTt8WBI",
  },
  {
    id: 36,
    title: "Magnetic Force Between Two Balls",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/magnetic-force-between-two-balls/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 37,
    title: "Sqrt(x)",
    topic: "Binary Search",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/sqrtx/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 38,
    title: "Smallest Good Base",
    topic: "Binary Search",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/smallest-good-base/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 39,
    title: "Find K Closest Elements",
    topic: "Binary Search",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-k-closest-elements/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== Sorting =====
  {
    id: 40,
    title: "Sort Colors",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sort-colors/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 41,
    title: "Reverse Pairs",
    topic: "Sorting",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/reverse-pairs/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 42,
    title: "Count of Smaller Numbers After Self",
    topic: "Sorting",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 43,
    title: "Sort an Array",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sort-an-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 44,
    title: "Merge Sorted Array",
    topic: "Sorting",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/merge-sorted-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 45,
    title: "Quick Sort",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/quick-sort/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 46,
    title: "Count Inversions",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/counting-inversions/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 47,
    title: "Sort Array By Parity",
    topic: "Sorting",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/sort-array-by-parity/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 48,
    title: "Minimum Absolute Difference",
    topic: "Sorting",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/minimum-absolute-difference/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 49,
    title: "K Closest Points to Origin",
    topic: "Sorting",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/k-closest-points-to-origin/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== Recursion =====
  {
    id: 50,
    title: "Print 1 to n using Recursion",
    topic: "Recursion",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/print-1-to-n-without-using-loops/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 51,
    title: "Print N to 1 without Loop",
    topic: "Recursion",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/print-n-to-1-without-using-loops/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 52,
    title: "Print N to 1 and 1 to N Using Recursion",
    topic: "Recursion",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/print-n-to-1-and-1-to-n-using-recursion/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 53,
    title: "Factorial",
    topic: "Recursion",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/factorial-of-a-number-using-recursion/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 54,
    title: "Pow(x, n)",
    topic: "Recursion",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/powx-n/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== Backtracking =====
  {
    id: 55,
    title: "N-Queens",
    topic: "Backtracking",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/n-queens/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 56,
    title: "Rat in a Maze",
    topic: "Backtracking",
    difficulty: "Hard",
    link: "https://www.geeksforgeeks.org/rat-in-a-maze-backtracking-using-recursion/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 57,
    title: "Palindrome Partitioning",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/palindrome-partitioning/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 58,
    title: "Sudoku Solver",
    topic: "Backtracking",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/sudoku-solver/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 59,
    title: "Gray Code",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/gray-code/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 60,
    title: "Letter Combinations of a Phone Number",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 61,
    title: "Combination Sum III",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/combination-sum-iii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 62,
    title: "Subsets",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/subsets/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 63,
    title: "Permutations",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/permutations/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 64,
    title: "Permutations II",
    topic: "Backtracking",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/permutations-ii/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== Greedy =====
  {
    id: 65,
    title: "Candy",
    topic: "Greedy",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/candy/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 66,
    title: "Job Sequencing Problem",
    topic: "Greedy",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/job-sequencing-problem-loss-minimization/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 67,
    title: "Gas Station",
    topic: "Greedy",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/gas-station/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 68,
    title: "N meetings in one room",
    topic: "Greedy",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/n-meetings-in-one-room/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 69,
    title: "Activity Selection",
    topic: "Greedy",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/activity-selection-problem-greedy-algo-1/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 70,
    title: "Minimum Platforms",
    topic: "Greedy",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/minimum-number-platforms-required-railwaybus-station/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 71,
    title: "Maximize Sum Of Array After K Negations",
    topic: "Greedy",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/maximize-sum-of-array-after-k-negations/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 72,
    title: "Last Stone Weight",
    topic: "Greedy",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/last-stone-weight/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== Bit Manipulation =====
  {
    id: 73,
    title: "Check K-th Bit",
    topic: "Bit Manipulation",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/check-whether-k-th-bit-set-or-not/",
    platform: "gfg",
    videoLink: "https://www.youtube.com/watch?v=lN9lj83lVK8",
  },
  {
    id: 74,
    title: "Reverse Bits",
    topic: "Bit Manipulation",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/reverse-bits/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=lyj1BpGZ8QI",
  },
  {
    id: 75,
    title: "Sum of Two Integers",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sum-of-two-integers/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=DCCzKeRajdQ",
  },
  {
    id: 76,
    title: "Swap Two Numbers Using Bitwise",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/swap-two-numbers-without-using-third-variable/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 77,
    title: "Single Number",
    topic: "Bit Manipulation",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/single-number/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=hJIlLxGc424",
  },
  {
    id: 78,
    title: "Single Number II",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/single-number-ii/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=2sGMA4LR8pg",
  },
  {
    id: 79,
    title: "Maximum XOR of Two Numbers in an Array",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 80,
    title: "Position of Rightmost Set Bit",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/position-of-rightmost-set-bit/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 81,
    title: "Subarray with XOR less than k",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/count-subarrays-xor-less-k/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 82,
    title: "Total Hamming Distance",
    topic: "Bit Manipulation",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/total-hamming-distance/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== Math =====
  {
    id: 83,
    title: "Permutation Sequence",
    topic: "Math",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/permutation-sequence/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 84,
    title: "Max Points on a Line",
    topic: "Math",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/max-points-on-a-line/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 85,
    title: "Divide Two Integers",
    topic: "Math",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/divide-two-integers/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 86,
    title: "Fizz Buzz",
    topic: "Math",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/fizz-buzz/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 87,
    title: "Find Greatest Common Divisor of Array",
    topic: "Math",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/find-greatest-common-divisor-of-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 88,
    title: "Number of Common Factors",
    topic: "Math",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/number-of-common-factors/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 89,
    title: "Four Divisors",
    topic: "Math",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/four-divisors/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 90,
    title: "Largest Number That Divides X and is Co-prime with Y",
    topic: "Math",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/largest-number-that-divides-x-and-is-co-prime-with-y/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 91,
    title: "Number of Open Doors",
    topic: "Math",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/number-of-open-doors/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 92,
    title: "Factorial Trailing Zeroes",
    topic: "Math",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/factorial-trailing-zeroes/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 93,
    title: "Count Trailing Zeros",
    topic: "Math",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/count-trailing-zeroes-factorial-number/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 94,
    title: "Rectangle Area",
    topic: "Math",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/rectangle-area/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 95,
    title: "Check If Array Pairs Are Divisible by k",
    topic: "Math",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/check-if-array-pairs-are-divisible-by-k/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 96,
    title: "Distribute Candies",
    topic: "Math",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/distribute-candies/",
    platform: "leetcode",
    videoLink: null,
  },
];

// Google Crack Coding Series in Telugu intro video
export const googleSeriesIntro = {
  title: "Google Crack Coding Series in Telugu — Introduction",
  videoLink: "https://www.youtube.com/watch?v=5Qqly4rxqDU",
};

// Difficulty ordered set for filters
export const difficulties = ["Easy", "Medium", "Hard"];
