// DYNAMIC PROGRAMMING (Part 3 · DP) — DP patterns.
// 21 unique problems.
// 1D DP: 5 · String DP: 2 · Grid DP: 5 · Knapsack DP: 3 · Partition DP: 1 · DP on Trees: 5
// Note: 2D DP is part of the 27-topic list but has no explicit problem yet.
export const dsaProblems = [
  // ===== 1D DP =====
  {
    id: 1,
    title: "Climbing Stairs",
    topic: "1D DP",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/climbing-stairs/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=UQTvXqWxKvE",
  },
  {
    id: 2,
    title: "House Robber",
    topic: "1D DP",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/house-robber/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=k5MRvhAGQ6E",
  },
  {
    id: 3,
    title: "House Robber II",
    topic: "1D DP",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/house-robber-ii/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=e1c4KThCbUE",
  },
  {
    id: 4,
    title: "Friends Pairing Problem",
    topic: "1D DP",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/friends-pairing-problem/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 5,
    title: "Fibonacci Number",
    topic: "1D DP",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/fibonacci-number/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== Grid DP =====
  {
    id: 6,
    title: "Unique Paths",
    topic: "Grid DP",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/unique-paths/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=pUt21JEa1Sw",
  },
  {
    id: 7,
    title: "Unique Paths II",
    topic: "Grid DP",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/unique-paths-ii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 8,
    title: "Minimum Path Sum",
    topic: "Grid DP",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/minimum-path-sum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 9,
    title: "Dungeon Game",
    topic: "Grid DP",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/dungeon-game/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 10,
    title: "01 Matrix",
    topic: "Grid DP",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/01-matrix/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=ZTAseawuRpc",
  },

  // ===== String DP =====
  {
    id: 11,
    title: "Decode Ways",
    topic: "String DP",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/decode-ways/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=Ppv0MbzvRcc",
  },
  {
    id: 12,
    title: "Distinct Subsequences",
    topic: "String DP",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/distinct-subsequences/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== Knapsack DP =====
  {
    id: 13,
    title: "Coin Change",
    topic: "Knapsack DP",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/coin-change/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=R5tnHGLNLD4",
  },
  {
    id: 14,
    title: "Coin Change II",
    topic: "Knapsack DP",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/coin-change-ii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 15,
    title: "Target Sum",
    topic: "Knapsack DP",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/target-sum/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== Partition DP =====
  {
    id: 16,
    title: "Burst Balloons",
    topic: "Partition DP",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/burst-balloons/",
    platform: "leetcode",
    videoLink: null,
  },

  // ===== DP on Trees =====
  {
    id: 17,
    title: "Sum Root to Leaf Numbers",
    topic: "DP on Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sum-root-to-leaf-numbers/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 18,
    title: "Path Sum",
    topic: "DP on Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/path-sum/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 19,
    title: "Path Sum II",
    topic: "DP on Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/path-sum-ii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 20,
    title: "Path Sum III",
    topic: "DP on Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/path-sum-iii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 21,
    title: "Lowest Common Ancestor of a Binary Tree",
    topic: "DP on Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    platform: "leetcode",
    videoLink: null,
  },
];
