// ADVANCED DSA (Part 2) — Data Structures, 6 topics.
// 57 unique problems.
// Stacks: 13 · Linked Lists: 14 · Trees: 17 · Tries: 7 · Heaps: 6
export const dsaProblems = [
  // ===== Stacks =====
  {
    id: 97,
    title: "Largest Rectangle in Histogram",
    topic: "Stacks",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 98,
    title: "Longest Valid Parentheses",
    topic: "Stacks",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/longest-valid-parentheses/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 99,
    title: "Insert an Element at the Bottom of a Stack",
    topic: "Stacks",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/insert-an-element-at-the-bottom-of-a-stack/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 100,
    title: "Reverse a Stack",
    topic: "Stacks",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/reverse-a-stack-using-recursion/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 101,
    title: "Next Greater Element",
    topic: "Stacks",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/next-greater-element/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 102,
    title: "Previous Greater Element",
    topic: "Stacks",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/previous-greater-element/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 103,
    title: "Smaller on Left",
    topic: "Stacks",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/smaller-on-left/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 104,
    title: "Next Smaller Element",
    topic: "Stacks",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/next-smaller-element/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 105,
    title: "Stock Span Problem",
    topic: "Stacks",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/the-stock-span-problem/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 106,
    title: "Min Stack",
    topic: "Stacks",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/min-stack/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 107,
    title: "Evaluate Reverse Polish Notation",
    topic: "Stacks",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 108,
    title: "Daily Temperatures",
    topic: "Stacks",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/daily-temperatures/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 109,
    title: "Expression Contains Redundant Bracket",
    topic: "Stacks",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/expression-contains-redundant-bracket-or-not/",
    platform: "gfg",
    videoLink: null,
  },

  // ===== Linked Lists =====
  {
    id: 110,
    title: "Merge k Sorted Lists",
    topic: "Linked Lists",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/merge-k-sorted-lists/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 111,
    title: "Middle of the Linked List",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/middle-of-the-linked-list/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 112,
    title: "Linked List Cycle",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/linked-list-cycle/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=sP78rPvG4XA",
  },
  {
    id: 113,
    title: "Reverse Linked List",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/reverse-linked-list/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=4M9mXiwOAuM",
  },
  {
    id: 114,
    title: "Remove Nth Node From End of List",
    topic: "Linked Lists",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=3zYDxGxGjQo",
  },
  {
    id: 115,
    title: "Palindrome Linked List",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/palindrome-linked-list/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 116,
    title: "Linked List Cycle II",
    topic: "Linked Lists",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/linked-list-cycle-ii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 117,
    title: "Intersection of Two Linked Lists",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/intersection-of-two-linked-lists/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 118,
    title: "Reverse Linked List II",
    topic: "Linked Lists",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/reverse-linked-list-ii/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 119,
    title: "Sort List",
    topic: "Linked Lists",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/sort-list/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 120,
    title: "Convert Binary Number in a Linked List to Integer",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 121,
    title: "Remove Linked List Elements",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/remove-linked-list-elements/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 122,
    title: "Delete Node in a Linked List",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/delete-node-in-a-linked-list/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 123,
    title: "Merge Two Sorted Lists",
    topic: "Linked Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/merge-two-sorted-lists/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=jTN4fLXLwlc",
  },

  // ===== Trees =====
  {
    id: 124,
    title: "Binary Tree Preorder Traversal",
    topic: "Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/binary-tree-preorder-traversal/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 125,
    title: "Binary Tree Inorder Traversal",
    topic: "Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/binary-tree-inorder-traversal/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 126,
    title: "Binary Tree Postorder Traversal",
    topic: "Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/binary-tree-postorder-traversal/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 127,
    title: "Maximum Depth of Binary Tree",
    topic: "Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=7fNxSkv508k",
  },
  {
    id: 128,
    title: "Binary Tree Right Side View",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/binary-tree-right-side-view/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 129,
    title: "Insert into a Binary Search Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/insert-into-a-binary-search-tree/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 130,
    title: "Validate Binary Search Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/validate-binary-search-tree/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=rB25y6zqayY",
  },
  {
    id: 131,
    title: "Lowest Common Ancestor of a Binary Search Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=I6_DoixraQU",
  },
  {
    id: 132,
    title: "Search in a Binary Search Tree",
    topic: "Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/search-in-a-binary-search-tree/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 133,
    title: "Top View of Binary Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/top-view-of-a-binary-tree/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 134,
    title: "Bottom View of Binary Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/bottom-view-of-a-binary-tree/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 135,
    title: "Left View of Binary Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/left-view-of-a-binary-tree/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 136,
    title: "Right View of Binary Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/right-view-of-a-binary-tree/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 137,
    title: "Tree Boundary Traversal",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/boundary-traversal-of-binary-tree/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 138,
    title: "Binary Tree Zigzag Level Order Traversal",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=M_2IZf-g3qw",
  },
  {
    id: 139,
    title: "Diameter of a Binary Tree",
    topic: "Trees",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/diameter-of-a-binary-tree/",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 140,
    title: "Invert Binary Tree",
    topic: "Trees",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/invert-binary-tree/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=W0TWj9tr2YY",
  },

  // ===== Tries =====
  {
    id: 141,
    title: "Implement Trie (Prefix Tree)",
    topic: "Tries",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/implement-trie-prefix-tree/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=BOoR91es740",
  },
  {
    id: 142,
    title: "Implement Trie II",
    topic: "Tries",
    difficulty: "Medium",
    link: "https://www.naukri.com/code360/problems/implement-trie-ll_8230840?challengeSlug=coding-interview-prep",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 143,
    title: "Design Add and Search Words Data Structure",
    topic: "Tries",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=76nfH0pxUWA",
  },
  {
    id: 144,
    title: "Prefix and Suffix Search",
    topic: "Tries",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/prefix-and-suffix-search/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 145,
    title: "Number of Distinct Substrings in a String",
    topic: "Tries",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/number-of-distinct-substrings-in-a-string/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 146,
    title: "Count Distinct Substrings",
    topic: "Tries",
    difficulty: "Medium",
    link: "https://www.naukri.com/code360/problems/count-distinct-substrings_985286",
    platform: "gfg",
    videoLink: null,
  },
  {
    id: 147,
    title: "Find Shortest Unique Prefix for Every Word",
    topic: "Tries",
    difficulty: "Medium",
    link: "https://www.geeksforgeeks.org/find-shortest-unique-prefix-for-every-word-in-a-given-list/",
    platform: "gfg",
    videoLink: null,
  },

  // ===== Heaps =====
  {
    id: 148,
    title: "Find Median from Data Stream",
    topic: "Heaps",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/find-median-from-data-stream/",
    platform: "leetcode",
    videoLink: "https://www.youtube.com/watch?v=BUH5KXiFtaw",
  },
  {
    id: 149,
    title: "Find K Pairs with Smallest Sums",
    topic: "Heaps",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 150,
    title: "Find the Kth Smallest Sum of a Matrix With Sorted Rows",
    topic: "Heaps",
    difficulty: "Hard",
    link: "https://leetcode.com/problems/find-the-kth-smallest-sum-of-a-matrix-with-sorted-rows/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 151,
    title: "Kth Largest Element in an Array",
    topic: "Heaps",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 152,
    title: "Kth Largest Element in a Stream",
    topic: "Heaps",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
    platform: "leetcode",
    videoLink: null,
  },
  {
    id: 153,
    title: "Minimum Cost of Ropes",
    topic: "Heaps",
    difficulty: "Easy",
    link: "https://www.geeksforgeeks.org/connect-n-ropes-minimum-cost/",
    platform: "gfg",
    videoLink: null,
  },
];
